"api_token": "dacdabae3cfaaabced467274fadf0c5ad0fcf2d6343a76bfb4b1bb709ff98e2987773266b68aa535"
"project_id" : "148"
"base_path" : "/language"
"base_url" : "https://poznakhovskyy.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source" : "/en-GB/en-GB.com_ars.ini",
    "dest" : "Joomla! Downloads/en-GB.com_ars.ini",
    "translation" : "/%locale%/%locale%.com_ars.ini"
  },
  {
    "source" : "/en-GB/en-GB.page_faqs.ini",
    "dest" : "Joomla! Downloads/en-GB.page_faqs.ini",
    "translation" : "/%locale%/%locale%.page_faqs.ini"
  },
  {
    "source" : "/en-GB/en-GB.page_technical_requirements.ini",
    "dest" : "Joomla! Downloads/en-GB.page_technical_requirements.ini",
    "translation" : "/%locale%/%locale%.page_technical_requirements.ini"
  }
]
